services:
  database:
    image: postgres:alpine
    restart: always
    # ports:
    #   - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-myuser} -d ${POSTGRES_DB:-mydatabase} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - unipoint
  
  cache:
    image: redis:7-alpine
    restart: always
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - unipoint

  backend:
    build: ./backend
    image: ${DOCKER_REGISTRY:-ngtukien218}/unipoint-backend:${TAG:-latest}
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/api/actuator/health | grep UP" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - logs:/app/logs
    networks:
      - unipoint

  frontend:
    build: ./frontend
    image: ${DOCKER_REGISTRY:-ngtukien218}/unipoint-frontend:${TAG:-latest}
    restart: always
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - unipoint

  cloudflare:
    image: cloudflare/cloudflared:2024.6.0
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - frontend
    networks:
      - unipoint

volumes:
  logs:
  pg_data:
  redis_data:

networks:
  unipoint:
    driver: bridge
  


