spring:
  config:
    import: optional:file:.env[.properties]
  main:
    banner-mode: "off"
    time-zone: Asia/Ho_Chi_Minh
  application:
    name: backend

  datasource:
<<<<<<< HEAD
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?prepareThreshold=0
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
=======
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres

    username: ${POSTGRES_USER:postgres.xhuvxyfehnsxnwljwtwq}
    password: ${POSTGRES_PASSWORD:Helloxinchao1@}
>>>>>>> ba0542582644f08d9f9734a34f7c30ef7454adfd
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
<<<<<<< HEAD
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate.jdbc.time_zone: Asia/Ho_Chi_Minh

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          microsoft:
            client-id: ${MICROSOFT_CLIENT_ID}
            client-secret: ${MICROSOFT_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_REDIRECT_URI:{baseUrl}/login/oauth2/code/{registrationId}}
            scope:
              - openid
              - email
              - profile
              - User.Read
            authorization-grant-type: authorization_code
            client-name: Microsoft
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: sub

  app:
    oauth2:
      redirect:
        url: ${OAUTH2_REDIRECT_URL:http://localhost:3000/oauth-success}

jwt:
  secret: ${JWT_SECRET:VGhpc0lzQURldlNlY3JldEtleUZvckpXVFNpZ25pbmdPbmx5ISE=}
  expiration-ms: ${JWT_EXPIRATION_MS:900000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}

server:
  servlet:
    context-path: /api
  port: 8080
  forward-headers-strategy: framework
=======
      ddl-auto: validate
>>>>>>> ba0542582644f08d9f9734a34f7c30ef7454adfd

logging:
  level:
    root: warn

<<<<<<< HEAD
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

=======
server:
  port: 8081
>>>>>>> ba0542582644f08d9f9734a34f7c30ef7454adfd
