spring:
  main:
    banner-mode: "off"
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres

    username: ${POSTGRES_USER:postgres.xhuvxyfehnsxnwljwtwq}
    password: ${POSTGRES_PASSWORD:Helloxinchao1@}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: warn

server:
  port: 8081