spring:
  main:
    banner-mode: "off"
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:aws-1-ap-southeast-1.pooler.supabase.com}:${DB_PORT:6543}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres.xhuvxyfehnsxnwljwtwq}
    password: "${POSTGRES_PASSWORD:Matkhau@1234qwer!}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"
